//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbo_Product()
        {
            this.Carts = new HashSet<Cart>();
            this.dbo_Order = new HashSet<dbo_Order>();
        }
    
        public int PID { get; set; }
        public string PName { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbo_Order> dbo_Order { get; set; }
    }
}
